### ISSUE TITLE
Floating paddle

### ISSUE THREAD

**Issue by Sm00thiee** [lthoangg/se20#13]
Try to make paddles stop when releasing moving keys

**Comment by lthoangg** [comment]
It's easy part, you can also do it.

**Comment by lthoangg** [comment]
But actually no, i think we should keep it going that way. Doesnt matter!

**Comment by Sm00thiee** [comment]
I don't like it
Neither you!!!

**Comment by lthoangg** [comment]
Which i dont, i like that way it keep running.
