### ISSUE TITLE
[DES]Enhance media stuffs

### ISSUE THREAD

**Issue by Sm00thiee** [lthoangg/se20#15]
Border, Sound, Textbox, Paddle, Menu

**Comment by Sm00thiee** [comment]
@Ntrug1 please link your commits with this issue

**Comment by Ntrug1** [comment]
Already solve in these commits:
a984588e8781eaf129c3f8a45a5b91895453a074
481b08676cb15f6d1d980270e0a459abe2d8ce16
f9749981f1c0edd5826325c7e24e74d2cb2d1db7
9975f4265df4df7982c3d2ad22af1aefa0af6d1b
