### ISSUE TITLE
Should .gitignore .pyc files and reorganize your .py files

### ISSUE THREAD

**Issue by dinhanhx** [lthoangg/se20#23]
## What are .pyc files?
[Here](https://github.com/lthoangg/se20/tree/master/__pycache__) are binary files therefor you should ignore them.

## .gitignore
```
*.pyc
__pycache__
```
## .py files
Please divide them into folders.

**Comment by Sm00thiee** [comment]
Thanks for your advice

**Comment by dinhanhx** [comment]
Why did you close it? When you did not remove all .pyc files
