### ISSUE TITLE
[ALG] Add rules for the game?

### ISSUE THREAD

**Issue by Sm00thiee** [lthoangg/se20#25]
I think we should create a sourcing rule for the game to make it less bored

Here is a suggestion for the scoring rule, based on table tennis:
- The winner of a game is the first to 11 points. 
- There must be a gap of at least two points between opponents at the end of the game though, so if the score is 10-10, the game goes into extra play until one of the players has gained a lead of 2 points. 

Everyone is required to leave comments on this issue!

**Comment by lthoangg** [comment]
Sound great to me.

**Comment by Ntrug1** [comment]
What about the timer @lthoangg

**Comment by Sm00thiee** [comment]
> 
> 
> What about the timer @lthoangg

I don't think a timer is needed

**Comment by Ntrug1** [comment]
sure

**Comment by lthoangg** [comment]
> 
> 
> > What about the timer @lthoangg
> 
> I don't think a timer is needed

That's another "kind of" rule, 2 players have 1 minutes. Who has better score then win

**Comment by dtkienn** [comment]
i think it should be 7 or 9. 11 seems to take a lot of time for 1 match.

**Comment by Sm00thiee** [comment]
> 
> 
> > > What about the timer @lthoangg
> > 
> > 
> > I don't think a timer is needed
> 
> That's another "kind of" rule, 2 players have 1 minutes. Who has better score then win

So after click on Play, users will have to choose between Timer and Score?

**Comment by lthoangg** [comment]
i mean just an idea for rule, not doing it both (or maybe)

**Comment by Sm00thiee** [comment]
Please check out my branch for my updates!
@Ntrug1 design an after match screen

**Comment by Sm00thiee** [comment]
I misclicked on the wrong commit
